format_code_in_doc_comments = true
format_macro_matchers       = true
group_imports               = "StdExternalCrate"
imports_granularity         = "Module"
max_width                   = 100
newline_style               = "Unix"
normalize_comments          = true
tab_spaces                  = 4
